name: "Feature Request"
description: "Submit a proposal for a new feature"
title: "Feature: "
labels: [New Feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our feature request form.
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Feature description"
      description: "A clear and concise description of what the feature is."
      placeholder: "You should add ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CODE_OF_CONDUCT.md)"
          required: true